#!/usr/bin/env bash

# Easier if we keep .vimrc in version control under ~/.vim
ln -s ~/.vim/.vimrc ~/.vimrc

# Install pathogen so we don't have to let plugins crap all over the .vim directory
mkdir -p ~/.vim/autoload ~/.vim/bundle ~/.vim/plugin && \
curl -LSso ~/.vim/autoload/pathogen.vim https://tpo.pe/pathogen.vim

# Install NERDTree
git clone https://github.com/scrooloose/nerdtree.git ~/.vim/bundle/nerdtree


